name: CI/CD Sigma API

on:
  push:
    branches:
      - desenvolvimentoBackEnd

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t mantecsystems/sigma-api:latest .

      - name: Update service in Swarm
        run: |
          docker service update \
            --image mantecsystems/sigma-api:latest \
            sigma_sigma-api || \
          docker stack deploy -c sigma-api.yml sigma
