name: CI/CD Sigma API

on:
  push:
    branches:
      - desenvolvimentoBackEnd

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t mantecsystems/sigma-api:latest .

      - name: Push Docker image
        run: |
          docker push mantecsystems/sigma-api:latest

      - name: Force update Swarm service
        run: |
          docker service update \
            --force \
            --with-registry-auth \
            --image mantecsystems/sigma-api:latest \
            sigma_sigma-api